### ISSUE TITLE
Sharing iP code quality feedback [for @rjkoh]

### ISSUE THREAD

**Issue by soc-se-bot-red** [rjkoh/ip#3]
@rjkoh We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/duke/Storage.java` lines `125-125`](https://github.com/rjkoh/ip/blob/59cde402d8babae37ad9c6ae9c6411f3731a28a9/src/main/java/duke/Storage.java#L125..L125):

```java

        boolean beenCreated = false;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `26-29`](https://github.com/rjkoh/ip/blob/59cde402d8babae37ad9c6ae9c6411f3731a28a9/src/main/java/duke/Duke.java#L26..L29):

```java

    /**
     * You should have your own function to generate a response to user input.
     * Replace this stub with your completed method.
     */

```

Example from [`src/main/java/duke/Storage.java` lines `29-34`](https://github.com/rjkoh/ip/blob/59cde402d8babae37ad9c6ae9c6411f3731a28a9/src/main/java/duke/Storage.java#L29..L34):

```java

    /**
     * Read text file and obtain new array of tasks from it.
     *
     * @return new ArrayList of tasks.
     * @throws DukeException error reading file.
     */

```

Example from [`src/main/java/duke/Storage.java` lines `100-105`](https://github.com/rjkoh/ip/blob/59cde402d8babae37ad9c6ae9c6411f3731a28a9/src/main/java/duke/Storage.java#L100..L105):

```java

    /**
     * Write the tasks from current program into text file.
     *
     * @param tasks TaskList containing current list of tasks.
     * @throws DukeException error writing tasks.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

possible problems in commit [`92c88f3`](https://github.com/rjkoh/ip/commit/92c88f358e5ca2d4a87df0c6b48ccb34c9c13edd):

`Implemented FXML with GUI`

* Not in imperative mood (?)
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (no need to modify past commit messages).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by rjkoh** [comment]
Fixed in commit [204c5ff](https://github.com/rjkoh/ip/commit/204c5ff3eb86dd260a2e71de54b9c03337faebac)
